### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by ntakouris** [skeskinen/MeshWidgets#1]
Hello, your repository came up on slack and it turns out it is very intresting. There is one issue though; many people are concerned about the legal use of your code  - that is because a license is missing/not defined. May you please add a fitting license so we can use this legally?

**Comment by skeskinen** [comment]
Are you/anyone familiar with licensing in UE context? Like am I allowed to license the source and uasset files with e.g. MIT?

**Comment by skeskinen** [comment]
Also the plugin source files already have Epic's copyright notice. I'm not sure how I'm supposed to mark that the modifications are licensed with my license.

**Comment by eXifreXi** [comment]
Hey, in extract out of the FAQ of Unreal Engine:

> **What modifications can I make to the source code?**
> You can extend it, modify it, fork it, or integrate it with other software or libraries, with one exception: 
> You can’t combine the Unreal Engine code with code covered by a “Copyleft” license agreement which would directly or indirectly require the Unreal Engine to be governed by terms other than the EULA.
> 
> **Unacceptable Copyleft licenses include:** Software licensed under the GNU General Public License (GPL), Lesser GPL (LGPL) (unless you are merely dynamically linking a shared library), or Creative Commons Attribution-ShareAlike License.
> **Acceptable Non-Copyleft licenses include:** Software licensed under the BSD License, MIT License, Microsoft Public License, or Apache License.

Based on that, MIT is fine, if it fits your needs (:

**Comment by ntakouris** [comment]
Thanks @eXifreXi !
