### ISSUE TITLE
something error in this Plugins

### ISSUE THREAD

**Issue by baikety** [skeskinen/MeshWidgets#2]
I have use your Plugins In my project,but when i choose widget,the ue4.13.1 always crash

![p99n f s6tui h 8w0ga](https://cloud.githubusercontent.com/assets/15119068/19218658/504ed51a-8e32-11e6-971c-0034ac41d4e3.png)

**Comment by skeskinen** [comment]
It seems like some of the level editor component initialization/destruction stuff has changed in 4.13.1. 

As a "fix" in editor widget rendering is now disabled. At least it shouldn't crash anymore.
